import path from "node:path";
import { and, eq } from "drizzle-orm";
import { ROOT } from "../paths.ts";
import { DEFAULT_AGENTS, DEFAULT_ROLES } from "../runner/prompts.ts";
import { db, ensureDatabase, runMigrations } from "./client.ts";
import { agents, cards, roles, runs, settings } from "./schema.ts";

/**
 * Brings the database up to the current schema on boot, so a fresh clone — or a fresh postgres
 * — runs with no migration step of its own.
 *
 * A postgres server it cannot find the database on gets one first; see `ensureDatabase`. That is
 * nothing on PGlite, which makes its own, so this reads the same either way.
 *
 * The migrations under `drizzle/` are generated by drizzle-kit from `schema.ts` and are the
 * only thing that creates or alters a table; drizzle records which have run in its own
 * `__drizzle_migrations` table and applies each exactly once, so this is safe on every boot.
 * Adding a column is two commands: edit `schema.ts`, then `npm run db:generate`.
 *
 * What follows the migrations is data, not shape.
 */
export async function ensureSchema() {
  await ensureDatabase();
  await runMigrations(path.join(ROOT, "drizzle"));

  // The settings row is a singleton the UI edits in place, so it has to exist before the UI
  // can load. Column defaults fill the rest in.
  await db.insert(settings).values({ id: "default" }).onConflictDoNothing();

  // A server with no roles draws boards that nothing runs on, so the three kinds of station are
  // seeded. `onConflictDoNothing` on the unique name means an edited role survives the boot.
  for (const role of DEFAULT_ROLES) {
    await db.insert(roles).values(role).onConflictDoNothing();
    // The migration that turned the role enum into rows could not carry the prompts with it —
    // they live here, in TypeScript — so it wrote the rows empty and left this to fill them.
    // An edited prompt is not empty and is not touched.
    await db
      .update(roles)
      .set({ prompt: role.prompt })
      .where(and(eq(roles.name, role.name), eq(roles.prompt, "")));
  }

  // One agent, and only where there is none. An agent is a model endpoint; a fresh install
  // still needs something for the first card to run on, but a server that has agents already
  // keeps them — including the four a version before this one seeded, whose names have simply
  // stopped meaning anything.
  const [anyAgent] = await db.select({ id: agents.id }).from(agents).limit(1);
  if (!anyAgent)
    for (const agent of DEFAULT_AGENTS) await db.insert(agents).values(agent).onConflictDoNothing();

  // A run left `running` by a crash is never going to finish; nothing would ever clear it, and
  // the card it was working would sit `running` for good with no process behind it.
  await db
    .update(runs)
    .set({ status: "error", error: "interrupted by a server restart", finishedAt: new Date() })
    .where(eq(runs.status, "running"));
  await db
    .update(cards)
    .set({ status: "error", error: "interrupted by a server restart" })
    .where(eq(cards.status, "running"));
}
