import path from "node:path";
import { and, eq } from "drizzle-orm";
import { ROOT } from "../paths.ts";
import { DEFAULT_AGENTS, DEFAULT_ROLES } from "../runner/prompts.ts";
import { db, ensureDatabase, runMigrations } from "./client.ts";
import { agents, cards, roles, runs, settings } from "./schema.ts";

/**
 * Brings the database up to the current schema on boot, so a fresh clone — or a fresh postgres
 * — runs with no migration step of its own.
 *
 * A postgres server it cannot find the database on gets one first; see `ensureDatabase`. That is
 * nothing on PGlite, which makes its own, so this reads the same either way.
 *
 * The migrations under `drizzle/` are generated by drizzle-kit from `schema.ts` and are the
 * only thing that creates or alters a table; drizzle records which have run in its own
 * `__drizzle_migrations` table and applies each exactly once, so this is safe on every boot.
 * Adding a column is two commands: edit `schema.ts`, then `npm run db:generate`.
 *
 * What follows the migrations is data, not shape.
 */
export async function ensureSchema() {
  await ensureDatabase();
  await runMigrations(path.join(ROOT, "drizzle"));

  // The settings row is a singleton the UI edits in place, so it has to exist before the UI
  // can load. Column defaults fill the rest in.
  await db.insert(settings).values({ id: "default" }).onConflictDoNothing();

  // A server with no agents cannot refine, decompose or execute anything, and the four it
  // needs differ only by their prompt — so they are seeded rather than left as four forms to
  // fill in before the first task. `onConflictDoNothing` on the unique name means an edited
  // role or agent survives the next boot.
  //
  // Roles first: an agent without one will not insert, which is the FK doing what it is for.
  for (const role of DEFAULT_ROLES) {
    await db.insert(roles).values(role).onConflictDoNothing();
    // The migration that turned the role enum into rows could not carry the prompts with it —
    // they live here, in TypeScript — so it wrote the four rows empty and left this to fill
    // them. An edited prompt is not empty and is not touched.
    await db
      .update(roles)
      .set({ systemPrompt: role.systemPrompt })
      .where(and(eq(roles.name, role.name), eq(roles.systemPrompt, "")));
  }
  const seeded = new Map((await db.select().from(roles)).map((role) => [role.name, role.id]));
  for (const agent of DEFAULT_AGENTS) {
    const roleId = seeded.get(agent.role);
    if (!roleId) continue;
    await db.insert(agents).values({ name: agent.name, roleId }).onConflictDoNothing();
  }

  // A run left `running` by a crash is never going to finish; nothing would ever clear it, and
  // the card it was working would sit `running` for good with no process behind it.
  await db
    .update(runs)
    .set({ status: "error", error: "interrupted by a server restart", finishedAt: new Date() })
    .where(eq(runs.status, "running"));
  await db
    .update(cards)
    .set({ status: "error", error: "interrupted by a server restart" })
    .where(eq(cards.status, "running"));
}
