import path from "node:path";
import { eq } from "drizzle-orm";
import { ROOT } from "../paths.ts";
import { DEFAULT_AGENTS } from "../runner/prompts.ts";
import { db, runMigrations } from "./client.ts";
import { agents, cards, runs, settings } from "./schema.ts";

/**
 * Brings the database up to the current schema on boot, so a fresh clone — or a fresh postgres
 * — runs with no migration step of its own.
 *
 * The migrations under `drizzle/` are generated by drizzle-kit from `schema.ts` and are the
 * only thing that creates or alters a table; drizzle records which have run in its own
 * `__drizzle_migrations` table and applies each exactly once, so this is safe on every boot.
 * Adding a column is two commands: edit `schema.ts`, then `npm run db:generate`.
 *
 * What follows the migrations is data, not shape.
 */
export async function ensureSchema() {
  await runMigrations(path.join(ROOT, "drizzle"));

  // The settings row is a singleton the UI edits in place, so it has to exist before the UI
  // can load. Column defaults fill the rest in.
  await db.insert(settings).values({ id: "default" }).onConflictDoNothing();

  // A server with no agents cannot refine, decompose or execute anything, and the four it
  // needs differ only by their prompt — so they are seeded rather than left as four forms to
  // fill in before the first task. Every model setting is left inheriting from settings, so
  // configuring one endpoint configures all four. `onConflictDoNothing` on the unique name
  // means an edited agent survives the next boot.
  for (const agent of DEFAULT_AGENTS) {
    await db.insert(agents).values(agent).onConflictDoNothing();
  }

  // A run left `running` by a crash is never going to finish; nothing would ever clear it, and
  // the card it was working would sit `running` for good with no process behind it.
  await db
    .update(runs)
    .set({ status: "error", error: "interrupted by a server restart", finishedAt: new Date() })
    .where(eq(runs.status, "running"));
  await db
    .update(cards)
    .set({ status: "error", error: "interrupted by a server restart" })
    .where(eq(cards.status, "running"));
}
